dist: xenial

language: python
python:
  - '3.7'

services:
  - docker

install: true

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Gateway tests"
      stage: test
      script: ./scripts/build.sh

    - name: "Gateway release"
      stage: deploy
      script: ./scripts/release.sh
      # release only in:
        #  branch   develop
        #  tag      #.#.#
      if: (branch = develop) OR (tag =~ ^[0-9]+(\.[0-9]+){2}$)
