dist: xenial

language: python
python:
  - '3.7'

services:
  - docker

install: true

# build only the master branch or tags like #.#.#
branches:
  only:
    - master
    - /^[0-9]+(\.[0-9]+){2}$/

# use matrix to split jobs and only re-execute the failing one
matrix:
  fast_finish: true
  include:
    - name: "Gateway Manager tests"
      stage: test
      script: ./scripts/build.sh

    - name: "Gateway Manager release"
      stage: deploy
      script:
        # Login in dockerhub with write permissions (repos are public)
        - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
        - ./scripts/release.sh
      # release only in:
      #   - branch   master
      #   - tag      #.#.#
      #   - never in forks or pull requests
      if: |
        fork IS false AND \
        type != pull_request AND \
        ((branch = master) OR (tag =~ ^[0-9]+(\.[0-9]+){2}$))
