version: '2.1'

services:

  # ---------------------------------
  # Auth builder Container
  # ---------------------------------

  auth:
    image: gateway-manager
    build: ./gateway-manager
    volumes:
      - ./api-auth/aether-auth:/code
    command: help
    environment:
      DEBUG: null

      KEYCLOAK_GLOBAL_ADMIN: ${KEYCLOAK_GLOBAL_ADMIN:-admin}
      KEYCLOAK_GLOBAL_PASSWORD: ${KEYCLOAK_GLOBAL_PASSWORD:-password}
      KEYCLOAK_KONG_CLIENT: ${KEYCLOAK_KONG_CLIENT:-kong}

      BASE_DOMAIN: ${BASE_DOMAIN:-aether.local}
      BASE_HOST: ${BASE_HOST:-http://aether.local}
      KEYCLOAK_INTERNAL: ${KEYCLOAK_INTERNAL:-keycloak:8080}
      KONG_INTERNAL: ${KONG_INTERNAL:-kong:8001}
      MINIO_INTERNAL: ${MINIO_INTERNAL:-minio:9000}

      ZOOKEEPER_HOST: ${ZOOKEEPER_HOST:-zookeeper:32181}
      ZOOKEEPER_USER: ${ZOOKEEPER_USER:-zk-admin}
      ZOOKEEPER_PW: ${ZOOKEEPER_PW:-password}
      KAFKA_SECRET: ${KAFKA_SECRET:-secret}

    extra_hosts:
      - ${BASE_DOMAIN:-aether.local}:${KONG_IP:-192.168.9.10}
